name: maxxasisstantt
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_spinkit: ^5.0.0
  passcode_screen: ^2.0.1
  provider: ^5.0.0
  pinput: ^3.0.1
  salomon_bottom_bar: ^3.3.2
  dialog_flowtter: ^0.3.3
  dialogflow_flutter: ^1.0.0
  bubble: ^1.2.1
  flutter_chat_ui: ^1.6.9
  uuid: ^4.0.0
  path_provider: ^2.1.1
  open_filex: ^4.3.2
  mime: ^1.0.4
  intl: ^0.18.1
  image_picker: ^1.0.4
  file_picker: ^5.5.0
  firebase_auth: ^4.9.0
  firebase_core: ^2.15.1
  cloud_firestore: ^4.9.1
  json_annotation: ^4.8.1
  dio: ^4.0.4
  riverpod: ^1.0.0
  flutter_riverpod: ^1.0.3+1
  http: ^0.13.3
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  json_serializable: ^6.7.1
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/dialog_flow_auth.json
    - assets/messages.json
