name: maxxasisstantt
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_spinkit: ^5.0.0
  passcode_screen: ^2.0.1
  provider: ^5.0.0
  pinput: ^3.0.1
  salomon_bottom_bar: ^3.3.2
  dialog_flowtter: ^0.3.3
  dialogflow_flutter: ^1.0.0
  bubble: ^1.2.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/dialog_flow_auth.json
