// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFX2WR0Qj13-NgDQNGFd5sJrB-pvt31lg',
    appId: '1:949886207204:web:20870d58e49c8f350658f1',
    messagingSenderId: '949886207204',
    projectId: 'groupchat-51c84',
    authDomain: 'groupchat-51c84.firebaseapp.com',
    storageBucket: 'groupchat-51c84.appspot.com',
    measurementId: 'G-D9MWCD8098',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6pzQ9a-iXPyONFL7od6-gDkEhS6ML-FM',
    appId: '1:949886207204:android:783716df0fefe8a00658f1',
    messagingSenderId: '949886207204',
    projectId: 'groupchat-51c84',
    storageBucket: 'groupchat-51c84.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDQCrL0gDO8kmuggntz6k7n1_H1JRNvCc',
    appId: '1:949886207204:ios:1687204050100a320658f1',
    messagingSenderId: '949886207204',
    projectId: 'groupchat-51c84',
    storageBucket: 'groupchat-51c84.appspot.com',
    iosClientId: '949886207204-pgrj6tcfma2i4ck8ngsh9oudj2vtmb3f.apps.googleusercontent.com',
    iosBundleId: 'com.example.maxxasisstantt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDQCrL0gDO8kmuggntz6k7n1_H1JRNvCc',
    appId: '1:949886207204:ios:d6b2e1924f75c38b0658f1',
    messagingSenderId: '949886207204',
    projectId: 'groupchat-51c84',
    storageBucket: 'groupchat-51c84.appspot.com',
    iosClientId: '949886207204-481p0op2hccvjkaol5c06r0t7lldncqm.apps.googleusercontent.com',
    iosBundleId: 'com.example.maxxasisstantt.RunnerTests',
  );
}
